### ISSUE TITLE
RSS feed of the website provides invalid URLs for items

### ISSUE THREAD

**Issue by hleb-kastseika** [40ants/40ants.github.com#5]
As I mentioned in the title, RSS feed of the website (https://40ants.com/) provides invalid URLs for items. Here is the example:
`https://40ants.com/40ants.com/posts/Pushing-your-pulls-faster.html`

The reason - RSS feed uses relative URLs, and these links contain domain name of the website. You can check it in the feed - https://40ants.com/atom.xml

**Comment by svetlyak40wt** [comment]
Closing this issue because I've moved from Coleslaw to [Staticl](https://40ants.com/staticl/) for site generation and it hasn't such problem with URLs.

Pay attention, now I have english and russian blog posts in separate directories and rss feeds were moved to:

- https://40ants.com/posts/rss.xml
- https://40ants.com/ru/posts/rss.xml
